# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AiGenome
email: yangluo86@gmail.com
description: > # Blogging on genomics, bioinformatics, news, pipelines and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AiGene.com" # the base hostname & protocol for your site
twitter_username: yluo86
github_username:  yluo86

# Build settings
#markdown: kramdown
markdown: rdiscount #fix nested list in Markdown

# Permalinks
#permalink: pretty
relavitve_permalinks: true
